name: CI Pipeline - Test Engineering Project

# Bu pipeline ne zaman çalışacak?
# Her 'push' işleminde ve her 'pull request'te çalışsın.
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Sanal bir Linux makinede çalışacak

    steps:
    # 1. Adım: GitHub deposundaki kodları bu sanal makineye çek
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Adım: Python 3.10 kurulumu yap
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # 3. Adım: Kütüphaneleri yükle (requirements.txt)
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 4. Adım: Unit Testleri Çalıştır (Coverage Raporu ile)
    # [PDF Madde 5.2 & 5.3]
    - name: Run Tests with Pytest & Coverage
      run: |
        pytest -v --cov=. --cov-report=term-missing
